# Generated by Django 4.2 on 2023-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/img/mX79RHzayOI_JCIIjd9.jpg', upload_to='static/img'),
        ),
    ]
