# Generated by Django 4.2 on 2023-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
