# Generated by Django 4.2 on 2023-05-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_alter_author_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='TagsOfPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.posts')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.tag')),
            ],
        ),
    ]
