# Generated by Django 4.2 on 2023-05-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_alter_posts_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsofpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.posts'),
        ),
        migrations.AlterField(
            model_name='tagsofpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.tag'),
        ),
    ]
