# Generated by Django 4.2 on 2023-06-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_tagsofpost_post_alter_tagsofpost_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsesunderpost',
            unique_together={('response', 'post')},
        ),
    ]
