# Generated by Django 4.2 on 2023-05-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_rename_tags_tag_tagsofpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='responsesunderpost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='responsesunderpost',
            old_name='response_id',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tag_id',
        ),
    ]
