# Generated by Django 4.2 on 2023-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_alter_responsesunderpost_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
