# Generated by Django 4.2.2 on 2023-07-03 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0006_alter_responsesunderpost_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Даьа и время')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.posts')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Like',
                'verbose_name_plural': 'Blog Likes',
            },
        ),
    ]
