# Generated by Django 4.2.2 on 2023-07-04 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0007_bloglikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglikes',
            name='blog_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='askme.posts'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='bloglikes',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AnswerLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('blog_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='askme.response')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer Like',
                'verbose_name_plural': 'Answer Likes',
            },
        ),
    ]
