# Generated by Django 4.2.2 on 2023-07-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_alter_bloglikes_blog_post_alter_bloglikes_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_response', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.author')),
                ('response_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.response')),
            ],
        ),
    ]
