# Generated by Django 4.2.2 on 2023-07-07 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askme', '0009_answertoresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertoresponse',
            name='whom_to_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
