# Generated by Django 4.2 on 2023-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0012_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_public',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
