# Generated by Django 4.2 on 2023-07-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0013_alter_posts_date_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/img/default.webp', max_length=500, upload_to='static/img'),
        ),
    ]
