# Generated by Django 4.2 on 2023-07-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0014_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.TextField(default='static/img/default.webp', max_length=500),
        ),
    ]
