# Generated by Django 4.2 on 2023-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0015_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/digitalstackoverflow.appspot.com/o/avatars/default.jpg?alt=media&token=190294ea-eb6a-4b84-b01d-56988e1f9e87', max_length=500),
        ),
    ]
