# Generated by Django 4.2 on 2023-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0016_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/digitalstackoverflow.appspot.com/o/avatars%2Fdefault.jpg?alt=media', max_length=500),
        ),
    ]
