version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8001
#    command: sh -c "gunicorn --bind 0.0.0.0:8000 askme_permyakov.wsgi" # Проблема с css js файлами. А точнее с upload image.
    ports:
      - "80:8001"
    volumes:
      - static_data:/static/img

volumes:
  static_data:
