version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
